servo_node:
  ros__parameters:
    use_sim_time: true # sincronize with simulation time
    moveit_servo:
      status_topic: "status"
      command_out_type: "trajectory_msgs/JointTrajectory"
      # conjunction Servo and Robot -> controller has to be configured with the same topic name
      command_out_topic: "/helene_trajectory_controller/joint_trajectory" # output topic for joint commands
      publish_period: 0.01
      command_in_type: "speed_units"
      cartesian_command_in_topic: "/servo_node/delta_twist_cmds"
      joint_command_in_topic: "/servo_node/delta_joint_cmds" # input topic for joint commands
      move_group_name: "helene_arm"
      planning_frame: "base_link"
      ee_frame_name: "axis_6"
      robot_link_command_frame: "base_link"
      incoming_twist_stale_frame_tolerance: 0.5
      joint_limit_margin: 0.1
      global_breakpoint_threshold: 0.03 # threshold for global breakpoint
      lower_singularity_threshold: 17.0 
      hard_stop_singularity_threshold: 30.0
      leaving_singularity_threshold_multiplier: 2.0
      check_collisions: false # true when using servo with a real robot, false when using servo in simulation
      collision_check_rate: 10.0
      collision_distance_safety_threshold: 0.05
      min_allowable_collision_distance: 0.01
      low_pass_filter_coeff: 1.5
      # Scale factors for the servo commands
      scale:
        linear: 0.02 # scale factor for linear commands
        rotational: 0.05
        joint: 0.02
