servo_node:
  ros__parameters:
    use_sim_time: false 
    moveit_servo:
      status_topic: "status"
      command_out_type: "std_msgs/Float64MultiArray"
      command_out_topic: "/helene_velocity_controller/commands"
      publish_joint_positions: false
      publish_joint_velocities: true
      publish_joint_accelerations: false
      publish_period: 0.01
      
      # --- CONFIGURAZIONE CARTESIANA REALE ---
      command_in_type: "speed_units" # Cambiato in speed_units (vuole TwistStamped)
      cartesian_command_in_topic: "/spacenav/twist_stamped" # Ascolta il nostro convertitore inline!
      joint_command_in_topic: "/servo_node/delta_joint_cmds"
      
      move_group_name: "helene_arm"
      planning_frame: "base_link"
      ee_frame_name: "axis_6"
      robot_link_command_frame: "base_link" # Impostato su base_link per muoversi coerentemente col mondo
      incoming_twist_stale_frame_tolerance: 0.5
      joint_limit_margin: 0.1
      global_breakpoint_threshold: 0.03
      
      lower_singularity_threshold: 0.005
      hard_stop_singularity_threshold: 0.01
      singularity_check_operator: "DLS"
      leaving_singularity_threshold_multiplier: 2.0
      check_collisions: false 
      collision_check_rate: 10.0
      collision_distance_safety_threshold: 0.05
      min_allowable_collision_distance: 0.01
      low_pass_filter_coeff: 0.15
      
      scale:
        linear: 0.15        
        rotational: 0.02   
        joint: 0.05