/**:
  ros__parameters:
    moveit_servo:
      use_gazebo: true
      status_topic: "~/status"
      
      # --- Incoming command topics ---
      # Set to "unitless" because our teleop node scales Newtons/Inputs directly into velocity before publishing
      command_in_type: "unitless"
      cartesian_command_in_topic: "~/delta_twist_cmds" 
      joint_command_in_topic: "~/delta_joint_cmds"     
      
      # --- Command output matching your exact controller configuration ---
      # In line with your ROS 2 control controller name
      command_out_topic: "/helene_trajectory_controller/joint_trajectory" 
      command_out_type: "trajectory_msgs/JointTrajectory"
      
      publish_period: 0.01                
      incoming_command_timeout: 0.1       
      
      # --- Robot Frames & Groups (Aligned with helene.srdf) ---
      # Matches exactly the <group name="helene_arm"> inside your SRDF
      move_group_name: "helene_arm"       
      planning_frame: "base_link"         
      
      # ee_frame_name: Must be the last link of your chain (axis_6)
      ee_frame_name: "axis_6"  
      
      # robot_link_command_frame: The frame in which your Twist commands are interpreted. 
      # Since your teleop node uses 'base_link', keep this as 'base_link' to move relative to the robot base.
      robot_link_command_frame: "base_link"
      
      # --- Joint limits and scaling ---
      linear_scale: 0.4
      rotational_scale: 0.8
      joint_scale: 0.5
      
      # --- Safety Thresholds ---
      check_collisions: false # Set to false for initial testing, but should be true for real robot operation
      collision_check_rate: 10.0
      self_collision_proximity_threshold: 0.01
      scene_collision_proximity_threshold: 0.02
      lower_singularity_threshold:  17.0
      hard_stop_singularity_threshold: 30.0