[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 460800

lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio.git
    br3ttb/PID @ ^1.2.1

build_flags =
    -D RCLC_EXECUTOR_MAX_NUM_HANDLERS=4
    -D MICROROS_TRANSPORTS_SERIAL
    ; Macro nativa per forzare la riconfigurazione di micro-ROS su PlatformIO
    -D micro_ros_transport=serial
    -D micro_ros_custom_build=default