[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.f_cpu = 240000000L

; micro-ROS (Humble)
board_microros_distro = humble
board_microros_transport = serial

; Library Dependency Finder (LDF) mode
lib_ldf_mode = deep

lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio.git
    protocentral/ProtoCentral ADS1220 24-bit ADC Library
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    adafruit/Adafruit BusIO
    https://github.com/miwagner/ESP32-Arduino-CAN.git
    br3ttb/PID
    https://github.com/LachlanGunn/oic.git
    https://github.com/ZoetropeLabs/AS5048A-Arduino.git

build_flags =
    -D ESP32_
    -I include